-- Per-user cloze (fill-in-the-blank) practice exercises generated by the LLM
-- from a news_items transcript. Each row is one reusable exercise: a
-- simplified article with {{0}} {{1}} ... placeholders plus a parallel
-- blanks array describing what each placeholder should be.
--
-- simplified_text: the LLM-rewritten short article. Placeholders are
--                  literal `{{N}}` substrings where N is the 0-based index
--                  into blanks_json. The frontend splits on these to render
--                  inputs inline.
--
-- blanks_json:     JSON array of:
--                    { answer, category, hint?, explanation_zh }
--                  category ∈ 'word' | 'phrase' | 'idiom' | 'collocation'
--                  Length MUST equal the count of {{N}} occurrences.
--
-- last_attempt_json: optional snapshot of the most recent grade pass:
--                    { answers: [...], score: 0.0..1.0, graded_at: "..." }
--                    Single attempt only — redoing overwrites.
--
-- Source news metadata (title/topic/language) is denormalized because
-- news_items is a global cache that can be evicted; we don't want exercises
-- to lose their source context if the underlying row disappears.
CREATE TABLE cloze_exercises (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  news_id           INTEGER NOT NULL REFERENCES news_items(id) ON DELETE CASCADE,

  source_title      TEXT NOT NULL,
  source_topic      TEXT NOT NULL,
  source_language   TEXT NOT NULL DEFAULT 'en',
  difficulty        TEXT NOT NULL DEFAULT 'normal'
    CHECK (difficulty IN ('easy', 'normal', 'hard')),

  simplified_text   TEXT NOT NULL,
  blanks_json       TEXT NOT NULL DEFAULT '[]',
  last_attempt_json TEXT,

  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX idx_cloze_exercises_user_created
  ON cloze_exercises(user_id, created_at DESC);
CREATE INDEX idx_cloze_exercises_news
  ON cloze_exercises(news_id);
